---
# Default variables for void-desktop role

# Install GNOME
void_install_gnome: false

# Install KDE
void_install_kde: false

# Install XFCE
void_install_xfce: false

# Install GNOME apps
void_install_gnome_apps: false

# Install minimal GNOME core
void_install_gnome_minimal: false

# Install XFCE apps
void_install_xfce_apps: false

# Display manager
void_display_manager: "gdm"
void_enable_display_manager: false

# Display manager configuration
void_display_manager_config: {}

# Common desktop packages
void_gnome_packages:
  - gnome
  - gdm

void_kde_packages:
  - kde-plasma
  - kde-baseapps
  - sddm

void_xfce_packages:
  - xfce4
  - lightdm

# Display manager packages
void_display_manager_packages:
  - gdm
  - sddm
  - lightdm
