---
# Containers and Virtual Machines (3.22, 3.22.1, 3.22.2, 3.22.3)
# Chroots and Containers, libvirt, LXC

- name: Install container packages
  xbps:
    name:
      - docker
      - podman
      - lxc
      - libvirt
      - qemu
      - virt-manager
    state: present
  when: void_install_container_packages | default(true)

- name: Install Docker packages
  xbps:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: present
  when: void_install_docker | default(false)

- name: Install Podman packages
  xbps:
    name:
      - podman
      - podman-compose
      - buildah
      - skopeo
    state: present
  when: void_install_podman | default(false)

- name: Install LXC packages
  xbps:
    name:
      - lxc
      - lxc-templates
      - lxcfs
    state: present
  when: void_install_lxc | default(false)

- name: Install libvirt packages
  xbps:
    name:
      - libvirt
      - qemu
      - virt-manager
      - virt-viewer
    state: present
  when: void_install_libvirt | default(false)

- name: Configure Docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    backup: yes
  when: void_docker_config is defined

- name: Configure Podman
  template:
    src: containers.conf.j2
    dest: /etc/containers/containers.conf
    backup: yes
  when: void_podman_config is defined

- name: Configure LXC
  template:
    src: lxc.conf.j2
    dest: /etc/lxc/lxc.conf
    backup: yes
  when: void_lxc_config is defined

- name: Configure libvirt
  template:
    src: libvirt.conf.j2
    dest: /etc/libvirt/libvirt.conf
    backup: yes
  when: void_libvirt_config is defined

- name: Enable container services
  runit:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ void_container_services | default([]) }}"
  when: void_container_services is defined
