---
# WiFi configuration (3.13.2 - wpa_supplicant, 3.13.3 - IWD)
# Based on https://docs.voidlinux.org/config/network/index.html

- name: Install WiFi packages
  xbps:
    name: "{{ void_common_wifi_packages }}"
    state: present

- name: Enable wpa_supplicant
  runit:
    name: wpa_supplicant
    state: started
    enabled: yes
  when: void_enable_wpa_supplicant | default(true)

- name: Enable iwd
  runit:
    name: iwd
    state: started
    enabled: yes
  when: void_enable_iwd | default(false)

- name: Configure wpa_supplicant
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    backup: yes
  when: void_wpa_supplicant_config is defined

- name: Configure IWD
  template:
    src: iwd.conf.j2
    dest: /etc/iwd/main.conf
    backup: yes
  when: void_iwd_config is defined
