---
# Locales and Translations (3.3)

- name: Install locale packages
  xbps:
    name:
      - glibc-locales
      - musl-locales
      - locale
    state: present
  when: void_install_locale_packages | default(true)

- name: Configure system locale
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
    backup: yes
  when: void_locale_config is defined

- name: Generate locales
  command: "locale-gen {{ item }}"
  loop: "{{ void_locales_to_generate | default([]) }}"
  when: void_locales_to_generate is defined

- name: Set system locale
  locale_gen:
    name: "{{ void_system_locale | default('en_US.UTF-8') }}"
    state: present
  when: void_system_locale is defined

- name: Configure keyboard layout
  template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    backup: yes
  when: void_keyboard_config is defined

- name: Configure timezone
  timezone:
    name: "{{ void_timezone | default('UTC') }}"
  when: void_timezone is defined

- name: Install translation packages
  xbps:
    name: "{{ item }}"
    state: present
  loop: "{{ void_translation_packages | default([]) }}"
  when: void_translation_packages is defined
