---
galaxy_info:
  author: void-linux-ansible
  description: User and group management for Void Linux
  company: Void Linux Community
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Void Linux
      versions:
        - all
  galaxy_tags:
    - void
    - linux
    - users
    - groups
dependencies: []
