---
# Desktop environments (3.16.7 - GNOME, 3.16.8 - KDE)
# Based on https://docs.voidlinux.org/config/graphical-session/gnome.html
# Based on https://docs.voidlinux.org/config/graphical-session/kde.html

- name: Install GNOME packages
  xbps:
    name: "{{ void_gnome_packages }}"
    state: present
  when: void_install_gnome | default(false)

- name: Install GNOME apps (optional)
  xbps:
    name: gnome-apps
    state: present
  when: void_install_gnome_apps | default(false)

- name: Install minimal GNOME core
  xbps:
    name: gnome-core
    state: present
  when: void_install_gnome_minimal | default(false)

- name: Install KDE packages
  xbps:
    name: "{{ void_kde_packages }}"
    state: present
  when: void_install_kde | default(false)

- name: Install XFCE packages
  xbps:
    name: "{{ void_xfce_packages }}"
    state: present
  when: void_install_xfce | default(false)

- name: Install XFCE apps (optional)
  xbps:
    name: xfce4-apps
    state: present
  when: void_install_xfce_apps | default(false)

- name: Install display manager packages
  xbps:
    name: "{{ void_display_manager_packages }}"
    state: present
  when: void_enable_display_manager | default(false)

- name: Configure display manager
  template:
    src: "{{ void_display_manager_config.template }}"
    dest: "{{ void_display_manager_config.dest }}"
    backup: yes
  when: void_display_manager_config is defined

- name: Enable display manager
  runit:
    name: "{{ void_display_manager | default('gdm') }}"
    state: started
    enabled: yes
  when: void_enable_display_manager | default(false)

- name: Enable dbus service (required for display managers)
  runit:
    name: dbus
    state: started
    enabled: yes
  when: void_enable_display_manager | default(false)
