---
- name: Configure Wayland session
  hosts: localhost
  become: yes
  tasks:
    - name: Create SDDM config directory
      ansible.builtin.file:
        path: /etc/sddm.conf.d
        state: directory
        mode: '0755'

    - name: Configure SDDM to use Wayland
      ansible.builtin.copy:
        dest: /etc/sddm.conf.d/wayland.conf
        content: |
          [General]
          DisplayServer=wayland
          GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

          [Wayland]
          CompositorCommand=kwin_wayland --drm --no-lockscreen
          SessionDir=/usr/share/wayland-sessions

    - name: Set default session to plasma wayland
      ansible.builtin.copy:
        dest: /var/lib/sddm/state.conf
        content: |
          [Last]
          Session=/usr/share/wayland-sessions/plasma.desktop