---
- name: Configure user environment
  hosts: localhost
  become: yes
  tasks:
    - name: Install input group for all users
      ansible.builtin.user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
        groups: input
        append: yes

    - name: Create KDE config directory
      ansible.builtin.file:
        path: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}/.config"
        state: directory
        owner: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
        group: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
        mode: '0755'

    - name: Configure Plasma Wayland settings
      ansible.builtin.copy:
        dest: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}/.config/plasma-workspace/env/wayland.sh"
        content: |
          #!/bin/sh
          export MOZ_ENABLE_WAYLAND=1
          export QT_QPA_PLATFORM=wayland
          export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
          export XDG_SESSION_TYPE=wayland
          export XDG_CURRENT_DESKTOP=KDE
          export KWIN_DRM_NO_AMS=1
        mode: '0755'
        owner: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
        group: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"