---
- name: Install and configure KDE Plasma 6
  hosts: localhost
  become: yes
  tasks:
    - name: Install KDE Plasma 6 and required packages
      community.general.xbps:
        name:
          - plasma-desktop
          - plasma-wayland
          - sddm
          - dolphin
          - konsole
          - plasma-pa
          - plasma-nm
          - kde-cli-tools
          - kscreen
          - powerdevil
          - bluedevil
          - plasma-disks
          - plasma-systemmonitor
          - plasma-firewall
          - plasma-browser-integration
          - kwalletmanager
          - ark
          - gwenview
          - okular
        state: present

    - name: Enable SDDM service
      ansible.builtin.file:
        path: /etc/sv/sddm
        src: /etc/sv/sddm
        state: link
        force: yes

    - name: Enable SDDM in runit
      ansible.builtin.file:
        path: /var/service/sddm
        src: /etc/sv/sddm
        state: link
        force: yes